# Generated by Django 3.0.1 on 2020-01-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a item genre (e.g. laptop, P.C etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Ticket', primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('bill_number', models.CharField(max_length=13, verbose_name='bill_number')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('ticket_severity', models.CharField(blank=True, choices=[('1', 'urgent'), ('2', 'Medium'), ('3', 'Low')], default='2', help_text='Ticket Severity', max_length=1)),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.Agent')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='Product.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='TicketInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('C', 'Closed'), ('A', 'Available')], default='d', help_text='Ticket availability', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.Ticket')),
            ],
        ),
    ]
